### PR TITLE
fix(App): Add some fixes and improvements

### LINKED ISSUE #103: App Error when updating Profile Data
Change e-mail (sample input)
image

Result
image

### LINKED ISSUE #113: While checking out, 'undefined' status while retrieving data
image

### PR DESCRIPTION
**Pull request by sianlasaga**
Bugfixes:
- fix #103 
- Fix bug where the blocked list doesn't display anything if one blocked peer doesn't exits
- fix #113 
- Fix bug where followers don't display when one user doesn't exists

Additions:
- re #110 
- Profile redirect when pressing the user's name in Order view

### CODE REVIEW

File: src/contexts/CurrentUserContext.ts [hunk 1]
```diff
@@ -1,9 +1,12 @@
 import React from 'react'
 import Profile from '../models/Profile'
+import Settings from '../models/Settings'
 
 const currentUser = new Profile()
+const settings = new Settings()
```
Comment (24thsaint) [inline src/contexts/CurrentUserContext.ts]: Should we handle changes? Like `updateCurrentSettings`?
Or we can just disregard it for the meantime?

File: src/Routes.tsx [hunk 2]
```diff
@@ -29,7 +28,7 @@ interface RouteProps {
 
 const Routes = ({ history }: RouteProps) => (
   <CurrentUserContext.Consumer>
-    {({ currentUser, updateCurrentUser }) => (
+    {({ currentUser, settings, updateCurrentUser }) => (
```
Comment (24thsaint) [inline src/Routes.tsx]: Ohh, awesome. I was thinking about this recently but my idea was to attach it to the `currentUser` and access it via `currentUser.settings`, however, I feel the the user object would be bloated. I like your approach more.
